### ISSUE TITLE
Incomprension

### ISSUE THREAD

**Issue by Marplex** [ALCC01/ClassevivaAPI#1]
What this mean? 
start=" + parseInt(((new Date).getTime() / 1000 - 86400)) + "&end=" + parseInt(((new Date).getTime() / 1000 + 86400 \* 7));

it comes from app.get('/:sessionId/agenda', function (req, res)

**Comment by ALCC01** [comment]
Those are arguments required by the backend system that handles the agenda, the first (`start=`) is the timestamp from which the system should start fetching the agenda content, the second one (`&end=`) it the timestamp at which it should stop.

I set arbitrary them to `now - 1d` and `now + 7d`, the result is a pretty awful code that I'm supposed to fix asap

**Comment by Marplex** [comment]
Perfect, thanks
