### ISSUE TITLE
Metodo agenda in session.js ritorna l'intero html della pagina invece che un json

### ISSUE THREAD

**Issue by Giuliopime** [ALCC01/ClassevivaAPI#13]
Il metodo agenda all'interno di Session.js, al contrario degli altri metodi di quella classe, prende l'html intero e non lo trasforma in json. Quindi risulta sempre errore

**Comment by andreafrati1969** [comment]
Occorre modificare il metodo agenda per usare family_base_url invece di base_url

**Comment by Giuliopime** [comment]
Non funziona comunque purtroppo

Questo è quello che ho provato:
```
let today = new Date();
let day = today.getDate();
let month = today.getMonth();
let from = new Date(2020, month, day, 8, 0, 0, 0)
let to = new Date(2020, month, day, 16, 0, 0, 0)
sessione.agenda(from, to)
    .then(agenda=>{
          console.log(agenda)
    }) 
```
Il console.log logga null

   ```
 this.agenda = (start, end) => {
        return this.request(this.family_base_url + 'agenda_studenti.php?ope=get_events&classe_id=&gruppo_id=&start=' + start + '&end=' + end)
            .then(res => {
                try {
                    return JSON.parse(res);
                } catch (err) {
                    throw new Error('Invalid or expired session ID')
                }
            })
    };
```

Queste sono le timestamp che passo ad Agenda per esempio:
`Thu May 21 2020 08:00:00 GMT+0200 (GMT+02:00)  Thu May 21 2020 16:00:00 GMT+0200 (GMT+02:00)`

**Comment by andreafrati1969** [comment]
Prova così, lo start e l'end sono secondi per cui devi dividere per 1000 quanto ritornato dal metodo Date.getTime().
var d = new Date('2020-05-01T00:00:00.000Z').getTime() / 1000;
    session.agenda(d, d).then(agenda => {
        console.log(agenda);
    })

**Comment by Giuliopime** [comment]
Funziona, grazie mille per il chiarimento, spero possa essere utile anche ad altri.

**Comment by Giuliopime** [comment]
Altre due domande scusa:
- quando uso il metodo grades, esso mi ritorna un oggetto vuoto
- quando do in input al metodo agenda una data futura, quindi ad esempio il giorno sucessivo, mi da errore, il return è null inoltre a volte non vengono ritornati tutti i compiti/note
